Refactored main andrestructured code
ray-chew/pyBELLA pull request #31
Opened 2024-12-18 17:24 UTC by ray-chew

`__main__.py` is now cleaned, and all the initialisation and analysis steps have been moved to their respective modules or subpackages.

2025-01-06 08:39 UTC, tbnc commented
I will review. 

Are the docs checks supposed to succeed?

2025-01-06 10:22 UTC, ray-chew commented
> I will review.
> 
> Are the docs checks supposed to succeed?

Thank you. The checks broke due to the renaming of the subpackages. This issue has been resolved with the latest commits. But the pytests are broken now, as I am in the midst of restructuring the diagnostics module to accept more general definitions of test cases.

2025-01-09 16:10 UTC, tbnc requested changes

2025-01-09 16:10 UTC, tbnc commented on README.md
> +pybella -ic rb -N 1
This does not appear to work, at least out of the box:

```
[nhad@ac6-101 pyBELLA]$ pybella -ic rb -N 1
Traceback (most recent call last):
  File "/home/nhad/.local/bin/pybella", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nhad/pyBELLA/src/__main__.py", line 30, in main
    sim_state = prepare.initialise()
                ^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nhad/pyBELLA/src/utils/prepare.py", line 43, in initialise
    ud.coriolis_strength = np.array(ud.coriolis_strength)
                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserDataInit' object has no attribute 'coriolis_strength'
```

2025-01-09 16:10 UTC, tbnc commented on run_scripts/test_dycore.py
> -import pytest
Line 74 in the README https://github.com/ray-chew/pyBELLA/blob/2165bed4ee231e34f8ad460d46877585d44fc737/README.md?plain=1#L74 should take into account the fact that the file has been deleted.

2025-01-09 16:10 UTC, tbnc commented on README.md
> +pybella -ic rb -N 1
This does not appear to work, at least not out of the box:

```
[nhad@ac6-101 pyBELLA]$ pybella -ic rb -N 1
Traceback (most recent call last):
  File "/home/nhad/.local/bin/pybella", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nhad/pyBELLA/src/__main__.py", line 30, in main
    sim_state = prepare.initialise()
                ^^^^^^^^^^^^^^^^^^^^
  File "/etc/ecmwf/nfs/dh1_home_b/nhad/pyBELLA/src/utils/prepare.py", line 43, in initialise
    ud.coriolis_strength = np.array(ud.coriolis_strength)
                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserDataInit' object has no attribute 'coriolis_strength'
```

2025-01-09 16:10 UTC, tbnc commented on src/data_assimilation/analysis.py
> +import logging
With a view to the forthcoming published version, I would propose removing commented code lines sooner rather than later unless still part of prototyping (which probably should not end up in develop anyway?) or there is another very compelling reason to keep them in.

2025-01-09 16:10 UTC, tbnc commented on src/flow_solver/discretisation/time_update.py
> +    mem,
Nice and compact

2025-01-10 09:16 UTC, tbnc requested changes

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> +    "dask",
2024.2.1

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "dill==0.3.6",
0.3.8

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "h5py==3.7.0",
3.12.1

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "matplotlib==3.5.1",
3.8.4

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "numba==0.56.4",
0.60.0

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "numpy==1.22.1",
1.26.4

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "PyYAML==6.0",
6.0.2

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "scipy==1.7.3",
1.14.1

2025-01-10 09:16 UTC, tbnc commented on pyproject.toml
> -    "termcolor==2.4.0"
2.4.0

2025-06-01 05:31 UTC, ray-chew commented on src/flow_solver/discretisation/time_update.py
> +    mem,
Thanks!

2025-06-07 08:05 UTC, closed without merging